
###
POST http://localhost:5001/user/signUp HTTP/1.1
Content-Type: application/json

{
    "name":"carlos",
    "lastname":"cjp",
    "email":"cjpd@gmail.com",
    "password":"123456",
    "confirmPassword":"123456"
}

###
POST http://localhost:5001/user/signUp HTTP/1.1
Content-Type: application/json

{
    "name":"javier",
    "lastname":"jav",
    "email":"jve.ca",
    "password":"123456",
    "confirmPassword":"123456"
}

###
GET http://localhost:5001/user HTTP/1.1

###
POST http://localhost:5001/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"cjpd@gmail.com",
    "password":"123456"
}

###
POST http://localhost:5001/departamento HTTP/1.1
Content-Type: application/json

{
   "nombre":"matematica"
}

###
POST http://localhost:5001/carrera HTTP/1.1
Content-Type: application/json

{
   "nombre":"industrial",
   "description":"aprueban todos",
   "idDepartamento":"664e57a1d94882e2ace128c1"
}

###
GET http://localhost:5001/departamento HTTP/1.1


###
POST  http://localhost:5001/projecto HTTP/1.1
Content-Type: application/json

{
    "titulo":"projecto de catedra",
    "description":"blabalblaoiwashfklajsfklj",
    "autor":"carlos",
    "idCarrera":"664e633f873cd255852930d8"
}

###
GET http://localhost:5001/carrera HTTP/1.1

###
GET http://localhost:5001/projecto HTTP/1.1

###
POST  http://localhost:5001/personal HTTP/1.1
Content-Type: application/json

{
   "name":"alfre",
    "lastname":"the god",
    "email":"affdsf@gmail.com",
    "projecto":"6660906c3da3142896d26a8f"
}

###
POST  http://localhost:5001/personal HTTP/1.1
Content-Type: application/json

{
   "name":"javier",
    "lastname":"pache",
    "email":"affhjgghkf@gmail.com",
    "projecto":"6660906c3da3142896d26a8f"
}

###
GET http://localhost:5001/personal HTTP/1.1

###
GET http://localhost:5001/personal/6660906c3da3142896d26a8f HTTP/1.1

###
GET http://localhost:5001/personal/geografia HTTP/1.1

###
GET http://localhost:5001/overall/projectsByType HTTP/1.1

###
GET http://localhost:5001/overall/total HTTP/1.1

###
GET http://localhost:5001/overall/totalRecent HTTP/1.1

###
POST  http://localhost:5001/eventog HTTP/1.1
Content-Type: application/json

{
    "title":"pueras bla bla",
    "start":"2024-01-01T00:00:00Z"
}

###
GET http://localhost:5001/eventog HTTP/1.1