
###
POST http://localhost:5001/user/signUp HTTP/1.1
Content-Type: application/json

{
    "name":"carlos",
    "lastname":"cjp",
    "email":"cjpd@gmail.com",
    "password":"123456",
    "confirmPassword":"123456"
}

###
POST http://localhost:5001/user/signUp HTTP/1.1
Content-Type: application/json

{
    "name":"javier",
    "lastname":"jav",
    "email":"jve.ca",
    "password":"123456",
    "confirmPassword":"123456"
}

###
GET http://localhost:5001/user HTTP/1.1

###
POST http://localhost:5001/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"cjpd@gmail.com",
    "password":"123456"
}

###
POST http://localhost:5001/departamento HTTP/1.1
Content-Type: application/json

{
   "nombre":"matematica"
}

###
POST http://localhost:5001/carrera HTTP/1.1
Content-Type: application/json

{
   "nombre":"mecanica",
   "description":"no tienen mujeres",
   "idDepartamento":"664e57a1d94882e2ace128c1"
}

###
GET http://localhost:5001/departamento HTTP/1.1